services:
  - type: web
    name: pepe-supply-demand-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
